(()=>{
'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(n/1000)*1000)+' ₽';
const moneyRange=(a,b)=>`${money(a)} — ${money(b)}`;
const progress=$('#scrollProgress'),sticky=$('#mobileSticky');let scrollRaf=0;
function animateNumber(el,to,duration=560,suffix=' ₽'){if(!el)return;const from=Number(el.dataset.current||String(el.textContent).replace(/\D/g,'')||0),start=performance.now();cancelAnimationFrame(el._raf);function tick(now){const t=Math.min(1,(now-start)/duration),v=Math.round(from+(to-from)*(1-Math.pow(1-t,3)));el.textContent=new Intl.NumberFormat('ru-RU').format(v)+suffix;if(t<1)el._raf=requestAnimationFrame(tick);else el.dataset.current=String(to)}el._raf=requestAnimationFrame(tick)}
function onScroll(){if(scrollRaf)return;scrollRaf=requestAnimationFrame(()=>{scrollRaf=0;const h=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(h>0?scrollY/h*100:0)+'%';sticky?.classList.toggle('show',scrollY>520);updateLoss();})}
addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll,{passive:true});
const scratchFine=$('#scratchFine'),scratchDeep=$('#scratchDeep');
if(scratchFine&&scratchDeep){let seed=61;const rnd=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296),ns='http://www.w3.org/2000/svg';const add=(root,x,y,len,ang,curve,deep=false)=>{const x2=x+Math.cos(ang)*len,y2=y+Math.sin(ang)*len,cx1=x+(x2-x)*.33+Math.sin(ang)*curve,cy1=y+(y2-y)*.33-Math.cos(ang)*curve,cx2=x+(x2-x)*.67-Math.sin(ang)*curve*.6,cy2=y+(y2-y)*.67+Math.cos(ang)*curve*.6,p=document.createElementNS(ns,'path');p.setAttribute('d',`M${x.toFixed(1)} ${y.toFixed(1)} C${cx1.toFixed(1)} ${cy1.toFixed(1)} ${cx2.toFixed(1)} ${cy2.toFixed(1)} ${x2.toFixed(1)} ${y2.toFixed(1)}`);p.setAttribute('opacity',deep?(.68+rnd()*.22).toFixed(2):(.28+rnd()*.34).toFixed(2));root.appendChild(p)};for(let i=0;i<82;i++){const cluster=i<46?0:i<70?1:2,x=cluster===0?90+rnd()*360:cluster===1?360+rnd()*320:650+rnd()*210,y=80+rnd()*470,len=14+rnd()*54,ang=[-.22,.12,1.18,2.88][i%4]+(rnd()-.5)*.42;add(scratchFine,x,y,len,ang,(rnd()-.5)*18)}for(let i=0;i<11;i++){const x=110+rnd()*700,y=90+rnd()*440,len=70+rnd()*120,ang=[-.18,.18,1.4,2.92][i%4]+(rnd()-.5)*.2;add(scratchDeep,x,y,len,ang,(rnd()-.5)*28,true)}}
const stage=$('#glassStage'),after=$('#afterLayer'),line=$('#splitLine'),handle=$('#splitHandle');let split=52,dragging=false,userTouched=false,startX=0,startY=0,horizontal=false;
function setSplit(pos,instant=false){if(!stage)return;split=Math.max(0,Math.min(100,pos));stage.style.setProperty('--split',split+'%');if(after)after.style.width=split+'%';if(line)line.style.left=split+'%';handle?.setAttribute('aria-valuenow',String(Math.round(split)));if(instant){after?.style.setProperty('transition','none');line?.style.setProperty('transition','none');requestAnimationFrame(()=>{after?.style.removeProperty('transition');line?.style.removeProperty('transition')})}$$('[data-glass]').forEach(b=>b.classList.toggle('active',(b.dataset.glass==='before'&&split<8)||(b.dataset.glass==='after'&&split>92)||(b.dataset.glass==='compare'&&split>=8&&split<=92)))}
function setFromX(x){const r=stage.getBoundingClientRect();setSplit((x-r.left)/r.width*100,true)}
if(stage){setSplit(52,true);stage.addEventListener('pointerdown',e=>{userTouched=true;dragging=true;horizontal=false;startX=e.clientX;startY=e.clientY;stage.setPointerCapture?.(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(!horizontal&&Math.abs(dx)>8&&Math.abs(dx)>Math.abs(dy))horizontal=true;if(horizontal){e.preventDefault();setFromX(e.clientX)}});const end=e=>{dragging=false;horizontal=false;stage.releasePointerCapture?.(e.pointerId)};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);handle?.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){userTouched=true;setSplit(split-5);e.preventDefault()}if(e.key==='ArrowRight'){userTouched=true;setSplit(split+5);e.preventDefault()}if(e.key==='Home'){userTouched=true;setSplit(0);e.preventDefault()}if(e.key==='End'){userTouched=true;setSplit(100);e.preventDefault()}});$$('[data-glass]').forEach(b=>b.addEventListener('click',()=>{userTouched=true;setSplit(b.dataset.glass==='before'?0:b.dataset.glass==='after'?100:52)}));if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){io.disconnect();if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;setTimeout(()=>{if(!userTouched)setSplit(8)},250);setTimeout(()=>{if(!userTouched)setSplit(92)},1200);setTimeout(()=>{if(!userTouched)setSplit(52)},2700)}},{threshold:.4});io.observe(stage)}}
const lossSection=$('.loss-section'),steps=$$('#lossSteps article'),lossMoney=$('#lossMoney'),lossDays=$('#lossDays'),lossProgress=$('#lossProgress');
function updateLoss(){if(!lossSection||!steps.length)return;const rect=lossSection.getBoundingClientRect();if(rect.top>innerHeight*.85||rect.bottom<innerHeight*.2)return;const mark=innerHeight*(matchMedia('(max-width:760px)').matches?.73:.63);let idx=-1;steps.forEach((step,i)=>{if(step.getBoundingClientRect().top<mark)idx=i});idx=Math.max(0,Math.min(steps.length-1,idx));steps.forEach((step,i)=>step.classList.toggle('active',i<=idx));let total=0,days=0;for(let i=0;i<=idx;i++){total+=Number(steps[i].dataset.money||0);days+=Number(steps[i].dataset.days||0)}if(Number(lossMoney?.dataset.value||0)!==total){lossMoney.dataset.value=String(total);animateNumber(lossMoney,total,420)}if(lossDays)lossDays.textContent=days+' '+(days===1?'день':days<5?'дня':'дней');if(lossProgress)lossProgress.style.width=((idx+1)/steps.length*100)+'%'}
const modes={replace:{label:'Сценарий A · Полная замена',title:'Разбираем готовую конструкцию и собираем процесс заново',money:312000,days:'18–21 день',outcome:'Риск переноса сроков',text:'Пять этапов и несколько исполнителей',active:['measure','production','delivery','dismantle','finish']},restore:{label:'Сценарий B · Восстановление',title:'Работаем с установленным стеклом непосредственно на объекте',money:96000,days:'около 2 дней',outcome:'Потенциальная экономия — 216 000 ₽',text:'Без производства, логистики и демонтажа',active:['measure','finish']}};
const scenarioLabel=$('#scenarioLabel'),scenarioTitle=$('#scenarioTitle'),scenarioMoney=$('#scenarioMoney'),scenarioDays=$('#scenarioDays'),scenarioOutcome=$('#scenarioOutcome'),scenarioOutcomeText=$('#scenarioOutcomeText'),timeline=$$('#timeline>div');let modeTouched=false;
function setMode(name,user=false){const m=modes[name];if(!m)return;if(user)modeTouched=true;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===name));scenarioLabel.textContent=m.label;scenarioTitle.textContent=m.title;animateNumber(scenarioMoney,m.money,620);scenarioDays.textContent=m.days;scenarioOutcome.textContent=m.outcome;scenarioOutcomeText.textContent=m.text;timeline.forEach(el=>el.classList.toggle('off',!m.active.includes(el.dataset.step)))}
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode,true)));setMode('replace');const scenarioBoard=$('#scenarioBoard');if(scenarioBoard&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){io.disconnect();setTimeout(()=>{if(!modeTouched)setMode('restore')},1000)}},{threshold:.4});io.observe(scenarioBoard)}
const form=$('#calculatorForm'),replacementRange=$('#replacementRange'),restorationRange=$('#restorationRange'),savingMoney=$('#savingMoney'),savingPercent=$('#savingPercent'),verdict=$('#calcVerdict'),replacementTime=$('#replacementTime'),restorationTime=$('#restorationTime');
function calculate(){if(!form)return null;const d=new FormData(form),object=Number(d.get('object')),area=Math.max(.2,Number(d.get('area'))||.2),pieces=Math.max(1,Number(d.get('pieces'))||1),damage=Number(d.get('damage')),access=Number(d.get('access')),urgency=Number(d.get('urgency')),known=Number(d.get('knownReplacement'))||0;let restore=Math.max(4000,(6100*area+1700*pieces)*object*damage*access*urgency),restLow=Math.round(restore*.88),restHigh=Math.round(restore*1.16),replacement=known;if(!replacement){replacement=(14500*area+23000*pieces+42000)*object*Math.max(1,.92*access);if(urgency>1.25)replacement*=1.08}const replLow=Math.round(replacement*.88),replHigh=Math.round(replacement*1.14),saveLow=Math.max(0,replLow-restHigh),saveHigh=Math.max(0,replHigh-restLow),pctLow=replLow?Math.max(0,Math.round(saveLow/replLow*100)):0,pctHigh=replHigh?Math.max(pctLow,Math.round(saveHigh/replHigh*100)):0;replacementRange.textContent=moneyRange(replLow,replHigh);restorationRange.textContent=moneyRange(restLow,restHigh);savingMoney.textContent=moneyRange(saveLow,saveHigh);savingPercent.textContent=`≈ ${pctLow}–${Math.min(67,pctHigh)}% относительно замены`;const restDays=urgency>=1.35?'день в день':area<=6?'от нескольких часов':area<=20?'1–3 дня':'от 3 дней';restorationTime.textContent=restDays;replacementTime.textContent=area>20?'18–28 дней':'14–21 день';verdict.textContent=saveHigh>90000?'Высокий потенциал экономии':'Восстановление имеет смысл рассмотреть';return{d,replLow,replHigh,restLow,restHigh,saveLow,saveHigh,restDays}}
form?.addEventListener('input',calculate);calculate();$('#sendCalculation')?.addEventListener('click',()=>{const r=calculate(),d=r.d,object=form.object.options[form.object.selectedIndex].text,damage=form.damage.options[form.damage.selectedIndex].text,access=form.access.options[form.access.selectedIndex].text,urgency=form.urgency.options[form.urgency.selectedIndex].text,text=`Здравствуйте. Хочу получить оценку восстановления стекла.\n\nОбъект: ${object}\nПлощадь: ${d.get('area')} м²\nЭлементов: ${d.get('pieces')}\nПовреждение: ${damage}\nДоступ: ${access}\nСрочность: ${urgency}\n\nРасчёт замены: ${replacementRange.textContent}\nРасчёт восстановления: ${restorationRange.textContent}\nПотенциальная экономия: ${savingMoney.textContent}\n\nГотов отправить фотографии.`;window.open('https://t.me/zhukov_boss?text='+encodeURIComponent(text),'_blank','noopener')});
const completion=$('#completionFlow');if(completion&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){completion.classList.add('visible');io.disconnect()}},{threshold:.35});io.observe(completion)}
$$('[data-track]').forEach(el=>el.addEventListener('click',()=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:el.dataset.track})}));
onScroll();updateLoss();
})();